config/routes.rb
Wiki::Application.routes.draw do
  get "users/show"
  get "users/create"
  get "users/destroy"
  get "users/index"
  get "users/new"


  resources :users do
    resources :trends
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :trends, only: [:create, :destroy, :index]
  resources :pages
  
  root "static_pages#index"
  
  #Users
  get "signup" => "users#new", :as => "signup"
  get "signin" => "sessions#new", :as => "signin"
  delete "signout" => "sessions#destroy", :as => "signout"
end

app/models/trend.rb
class Trend < ActiveRecord::Base
  attr_accessible :user_id, :title

  belongs_to :user
  has_many :pages

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 100 }
end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]

  def create
    @trend = current_user.trends.build(trend_params)
    if @trend.save
      flash[:success] = "Trend created!"
      redirect_to :back
    else
      render :back
    end
  end

  def destroy
    @trend = Trend.find(params[:id])
    if @trend.destroy
      redirect_to root_url
      flash[:success] = "Trend was successfully deleted!"
    end
  end

  def index    
    @user = User.find_by(params[:id])
    if @user
      @trend = @user.trends.build
    end
    @trends = Trend.all
  end

  private

    def trend_params
      params.require(:trend).permit(:title)
    end
end

app/helpers/trends_helper.rb
module TrendsHelper
end

app/views/trends/_trend_form.html.erb
<div class="form-group">
	<%= form_for(@trend) do |f| %>
        <%= render "shared/error", object: f.object %>
		<div class="input-group">
			<%= f.text_field :title, class: "form-control", id:"messagetrend", placeholder: "Compose new trend..." %>
			<span class="input-group-btn"><%= f.submit "Post", class: "btn btn-primary" %></span>
		</div>
		<p>You have <B><SPAN id="countdowntrend">100</SPAN></B> characters remaining.</p>
	<% end %>
</div>
<script>
function updateCountdown() {
    // 140 is the max message length
    var remaining = 100 - jQuery('#messagetrend').val().length;
    jQuery('#countdowntrend').text(remaining);
}

$(document).ready(function($) {
    updateCountdown();
    $('#messagetrend').change(updateCountdown);
    $('#messagetrend').keyup(updateCountdown);
});
</script>

app/views/trends/destroy.html.erb
<h1>Trends#destroy</h1>
<p>Find me in app/views/trends/destroy.html.erb</p>

app/views/trends/index.html.erb
<ul class="nav nav-tabs" id="myTab">
	<li><%= link_to "Trends", "#trendshow", :data => {:toggle=>"tab"} %></li>
	<li><%= link_to "New", "#new", :data => {:toggle=>"tab"} %></li>
</ul>
<div class="tab-content">
	<div class="tab-pane" id="trendshow">
		<h1>All Trends</h1>
		<% @trends.each do |trend| %>
			<h3><%= trend.title %></h3>
            <% if signed_in? %>
              	<% if current_user.admin %>
                	<p><%= button_to "Delete", trend_path(trend), method: :delete, data: { confirm: "You sure?", class: "btn btn-large" } %></p>
              	<% end %>
            <% end %>
				<ul>
            <% if trend.pages.any? %>
            	<% trend.pages.each do |page| %>
					<li><%= link_to page.title, page_path(page) %></li>
				<% end %>
            <% else %>
					<li>No pages yet</li>
            <% end %>
				</ul>
		<% end %>
	</div>
	<div class="tab-pane" id="new">
		<h1>Create a New Trend</h1>
		<% if signed_in? %>
		    <% if current_user.admin %>
			    <div class="form-group">
			      	<%= form_for(@trend) do |f| %>
			        	<%= render "shared/error", object: f.object %>
			        	<%= f.text_field :title, placeholder: "Compose new trend..." %>
			        	<%= f.submit "Post", class: "btn btn-xs btn-primary" %>
			      	<% end %>
			    </div>
			<% else %>
				<p>Sorry, but you are not logged in or not an admin.
		    <% end %>
		<% else %>
		    <p>You need to be signed in or an admin to make a new trend</p>
		<% end %>
	</div>
</div>
<script>
   	$('#myTab a:first').tab('show') // Select first tab
</script>