config/routes.rb
Wiki::Application.routes.draw do
  get "users/show"
  get "users/create"
  get "users/destroy"
  get "users/index"
  get "users/new"


  resources :users do
    resources :trends
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :trends, only: [:create, :destroy, :index]
  resources :pages
  
  root "static_pages#index"
  
  #Users
  get "signup" => "users#new", :as => "signup"
  get "signin" => "sessions#new", :as => "signin"
  delete "signout" => "sessions#destroy", :as => "signout"
end

app/views/shared/_error.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
      <h3>The form contains <%= pluralize(object.errors.count, "error") %>.</h3>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
	<div class="container">
		<p class="text-muted navbar-text"><%= link_to "All Users", users_index_path %></p>
		<p class="text-muted navbar-text"><%= link_to "All Trends", trends_path %></p>
	</div>
</nav>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <%= link_to "Wiki", root_path, {:class => "navbar-brand"} %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" >
        <ul class="nav navbar-nav pull-right">
            <% if signed_in? %>
                <% if current_user.admin %>
                <li class="dropdown">
                    <a id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="#">Admin <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                        <li><%= link_to "All Trends", trends_path %></li>
                        <li><%= link_to "All Users", users_index_path %></li>
                    </ul>
                </li>
                <% end %>
                <li><%= link_to current_user.username, user_path(current_user) %></li>
                <li><%= link_to "Create Page", new_page_path %></li>
                <li><%= link_to "Logout", signout_path, method: "delete"%></li>
            <% else %>
                <li><%= link_to "Signup", signup_path %></li>
                <li><%= link_to "Login", signin_path %></li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/shared/_left.html.erb
<div id="left">

  <!-- search -->
  <p><%= form_tag(pages_path, :method => 'get', :class => "search") do %>
    <%= text_field_tag :search, params[:search], class: "form-control", :placeholder => "Search" %>
  <% end %></p>
  <!-- end of search -->

  <!-- trend form -->
  <% if signed_in? %>
    <% if current_user.admin %>
    <%= render "trends/trend_form" %>
    <% end %>
  <% end %>
  <!-- end of trend form -->
  <div class="panel-group" id="accordion">
    <% @trends.each do |trend| %>
      <!-- start of panel 1 -->
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne-<%= trend.id %>">
                <%= trend.title %>
              </a>
            </h4>
          </div>
          <div id="collapseOne-<%= trend.id %>" class="panel-collapse collapse in">
            <div class="panel-body">
            <% if trend.pages.any? %>
              <% trend.pages.each do |page| %>
                  <p><%= link_to page.title, page_path(page) %></p>
              <%end%>
            <%else%>
              <p>No pages made</p>
            <%end%>
            </div>
          </div>
        </div>
    <% end %>
      <!-- end of panel 1 -->
  </div>
<script>
$('.collapse').collapse()
</script>
</div>